"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.10.5
  Module: dobot_atom.msg.dds_
  IDL file: amr_state.idl

"""

from enum import auto
from typing import TYPE_CHECKING, Optional
from dataclasses import dataclass

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import dobot_atom

class NavigationStatus_(idl.IdlEnum, typename="dobot_atom.msg.dds_.NavigationStatus_", default="UNKNOWN"):
    UNKNOWN = auto()
    QUEUING = auto()
    RUNNING = auto()
    COMPLETED = auto()
    FAILED = auto()
    PAUSED = auto()
    CANCELED = auto()
    WAITING_CONFIRM = auto()
    IDLE = auto()
    STOPPED = auto()
class DeviceStatus_(idl.IdlEnum, typename="dobot_atom.msg.dds_.DeviceStatus_", default="DEVUNKNOWN"):
    DEVUNKNOWN = auto()
    DEVIDLE = auto()
    TASKING = auto()
    ERROR = auto()
    OFFLINE = auto()
    INIT = auto()
    CHARGING = auto()
    UPGRADE = auto()

@dataclass
@annotate.final
@annotate.autoid("sequential")
class AMREventStatus_(idl.IdlStruct, typename="dobot_atom.msg.dds_.AMREventStatus_"):
    emergency_stop_pressed: bool
    enable_pressed: bool
    path_blocked: bool
    low_battery: bool
    obstacle_detected: bool


@dataclass
@annotate.final
@annotate.autoid("sequential")
class AMRBasicStatus_(idl.IdlStruct, typename="dobot_atom.msg.dds_.AMRBasicStatus_"):
    battery_level: types.float32
    battery_voltage: types.float32
    battery_current: types.float32
    heartbeat: types.uint16


@dataclass
@annotate.final
@annotate.autoid("sequential")
class AMRState_(idl.IdlStruct, typename="dobot_atom.msg.dds_.AMRState_"):
    device_status: 'dobot_atom.msg.dds_.DeviceStatus_'
    navigation_status: 'dobot_atom.msg.dds_.NavigationStatus_'
    basic_status: 'dobot_atom.msg.dds_.AMRBasicStatus_'
    position: types.array[types.float32, 3]
    amr_event: 'dobot_atom.msg.dds_.AMREventStatus_'
    error_code: types.array[types.uint32, 32]
    task_id: types.uint32
    work_mode: types.uint32


