"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.10.5
  Module: dobot_atom.msg.dds_
  IDL file: amr_cmd.idl

"""

from enum import auto
from typing import TYPE_CHECKING, Optional
from dataclasses import dataclass

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import dobot_atom

class AMRCommandType(idl.IdlEnum, typename="dobot_atom.msg.dds_.AMRCommandType", default="CANCEL_TASK"):
    CANCEL_TASK = auto()
    PAUSE_TASK = auto()
    RESUME_TASK = auto()
    MOVE_TO_TAG = auto()
    REMOTE_CONTROL = auto()
    ROTATE = auto()
    START_REMOTE = auto()
    STOP_REMOTE = auto()
    SUBSCRIBE_LASER = auto()
    UNSUBSCRIBE_LASER = auto()
    START_MAPPING = auto()
    SAVE_MAP = auto()
    STOP_MAPPING = auto()
    SET_VEL = auto()
    SET_ACCEL = auto()
    SET_DECEL = auto()

@dataclass
@annotate.final
@annotate.autoid("sequential")
class AMRCommand_(idl.IdlStruct, typename="dobot_atom.msg.dds_.AMRCommand_"):
    command_type: 'dobot_atom.msg.dds_.AMRCommandType'
    target_id: types.uint32
    linear_vel: types.float32
    angular_vel: types.float32
    command_id: types.uint32
    timestamp: types.uint64
    theta: types.float32


