"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.10.5
  Module: dobot_atom.msg.dds_
  IDL file: bms_state.idl

"""

from enum import auto
from typing import TYPE_CHECKING, Optional
from dataclasses import dataclass

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import dobot_atom


@dataclass
@annotate.final
@annotate.autoid("sequential")
class BmsState_(idl.IdlStruct, typename="dobot_atom.msg.dds_.BmsState_"):
    bms_state: types.uint16
    afe_state: types.uint16
    bms_alarms: types.uint32
    battery_level: types.uint16
    battery_health: types.uint16
    pcb_board_temp: types.uint16
    afe_chip_temp: types.uint16
    battery_now_current: types.uint16
    cells_voltage: types.array[types.uint16, 16]
    battery_pack_current_voltage: types.uint16
    battery_pack_io_voltage: types.uint16
    bms_work_time: types.uint32
    bms_hardware_version: types.uint16
    bms_software_version: types.uint16
    heartbeat: types.uint16


