"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.10.5
  Module: dobot_atom.msg.dds_
  IDL file: lowstate.idl

"""

from enum import auto
from typing import TYPE_CHECKING, Optional
from dataclasses import dataclass

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import dobot_atom


@dataclass
@annotate.final
@annotate.autoid("sequential")
class LowState_(idl.IdlStruct, typename="dobot_atom.msg.dds_.LowState_"):
    algs_mode: types.uint16
    imu_state: 'dobot_atom.msg.dds_.IMUState_'
    motor_state: types.array['dobot_atom.msg.dds_.MotorState_', 30]
    bms_state: 'dobot_atom.msg.dds_.BmsState_'
    wireless_remote: types.array[types.uint8, 40]
    reserve: types.uint32


