"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.10.5
  Module: dobot_atom.msg.dds_
  IDL file: main_nodes_state.idl

"""

from enum import auto
from typing import TYPE_CHECKING, Optional
from dataclasses import dataclass

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import dobot_atom


@dataclass
@annotate.final
@annotate.autoid("sequential")
class AxisStateInfo_(idl.IdlStruct, typename="dobot_atom.msg.dds_.AxisStateInfo_"):
    servo_state: types.uint8
    error_code: types.uint16
    warn_code: types.uint16
    pos_err_code: types.int32
    vel_err_code: types.int32
    torque_err_code: types.int32
    node_state: types.uint8
    display_op_mode: types.uint8
    is_virtual: bool
    mcu_temp: types.uint8
    mos_temp: types.uint8
    motor_temp: types.uint8
    bus_voltage: types.uint8
    software_version: types.uint16


@dataclass
@annotate.final
@annotate.autoid("sequential")
class EcatSlaveInfo_(idl.IdlStruct, typename="dobot_atom.msg.dds_.EcatSlaveInfo_"):
    is_virtual: bool
    slave_state: types.uint8
    error_code: types.uint16
    software_version: types.uint16


@dataclass
@annotate.final
@annotate.autoid("sequential")
class MainNodesState_(idl.IdlStruct, typename="dobot_atom.msg.dds_.MainNodesState_"):
    left_leg: types.array['dobot_atom.msg.dds_.AxisStateInfo_', 6]
    right_leg: types.array['dobot_atom.msg.dds_.AxisStateInfo_', 6]
    waist: 'dobot_atom.msg.dds_.AxisStateInfo_'
    left_arm: types.array['dobot_atom.msg.dds_.AxisStateInfo_', 7]
    right_arm: types.array['dobot_atom.msg.dds_.AxisStateInfo_', 7]
    head: types.array['dobot_atom.msg.dds_.AxisStateInfo_', 2]
    ecat2can: types.array['dobot_atom.msg.dds_.EcatSlaveInfo_', 2]


