"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.10.5
  Module: dobot_atom.msg.dds_
  IDL file: power_cmd.idl

"""

from enum import auto
from typing import TYPE_CHECKING, Optional
from dataclasses import dataclass

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import dobot_atom


@dataclass
@annotate.final
@annotate.autoid("sequential")
class PowerCmd_(idl.IdlStruct, typename="dobot_atom.msg.dds_.PowerCmd_"):
    control_power_supply: types.uint16
    clear_errors: types.uint16
    set_led_colour: types.uint16
    set_led_mode: types.uint16
    set_sd_brightness: types.uint16
    set_sd_mode: types.uint16


