"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.10.5
  Module: dobot_atom.msg.dds_
  IDL file: power_state.idl

"""

from enum import auto
from typing import TYPE_CHECKING, Optional
from dataclasses import dataclass

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import dobot_atom


@dataclass
@annotate.final
@annotate.autoid("sequential")
class PowerState_(idl.IdlStruct, typename="dobot_atom.msg.dds_.PowerState_"):
    power_supply_state: types.uint16
    strong_power_current: types.uint16
    weak_power_current: types.uint16
    weak_power_voltage: types.uint16
    replenishment_port_voltage: types.uint16
    hardware_version: types.uint16
    software_version: types.uint16
    error_codes: types.uint16
    heartbeat: types.uint16
    strong_power_voltage: types.uint16
    brk_2v5_voltage: types.uint16
    brk_state: types.uint16


