"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.10.5
  Module: dobot_atom.msg.dds_
  IDL file: remote_control.idl

"""

from enum import auto
from typing import TYPE_CHECKING, Optional
from dataclasses import dataclass

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import dobot_atom


@dataclass
@annotate.final
@annotate.autoid("sequential")
class JoystickValue_(idl.IdlStruct, typename="dobot_atom.msg.dds_.JoystickValue_"):
    x: types.float32
    y: types.float32


@dataclass
@annotate.final
@annotate.autoid("sequential")
class RemoteControl_(idl.IdlStruct, typename="dobot_atom.msg.dds_.RemoteControl_"):
    btn_move: 'dobot_atom.msg.dds_.JoystickValue_'
    btn_turn: 'dobot_atom.msg.dds_.JoystickValue_'


