"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.10.5
  Module: dobot_atom.msg.dds_
  IDL file: set_fsm_id.idl

"""

from enum import auto
from typing import TYPE_CHECKING, Optional
from dataclasses import dataclass

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import dobot_atom


@dataclass
@annotate.final
@annotate.autoid("sequential")
class SetFsmId_(idl.IdlStruct, typename="dobot_atom.msg.dds_.SetFsmId_"):
    id: types.uint16
    current_action: str


