"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.10.5
  Module: dobot_atom.msg.dds_
  IDL file: teleop_state.idl

"""

from enum import auto
from typing import TYPE_CHECKING, Optional
from dataclasses import dataclass

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import dobot_atom

class TeleopState(idl.IdlEnum, typename="dobot_atom.msg.dds_.TeleopState", default="DISABLED"):
    DISABLED = auto()
    ENABLING = auto()
    ENABLED = auto()

@dataclass
@annotate.final
@annotate.autoid("sequential")
class TeleopStatus_(idl.IdlStruct, typename="dobot_atom.msg.dds_.TeleopStatus_"):
    teleop_state: 'dobot_atom.msg.dds_.TeleopState'
    sync_state: 'dobot_atom.msg.dds_.TeleopState'
    record_state: 'dobot_atom.msg.dds_.TeleopState'


