"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.10.5
  Module: dobot_atom.msg.dds_
  IDL file: teleop_cmd.idl

"""

from enum import auto
from typing import TYPE_CHECKING, Optional
from dataclasses import dataclass

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import dobot_atom

class TeleopCommandType(idl.IdlEnum, typename="dobot_atom.msg.dds_.TeleopCommandType", default="START_SYNC"):
    START_SYNC = auto()
    STOP_SYNC = auto()
    START_TELEOP = auto()
    STOP_TELEOP = auto()
    START_RECORD = auto()
    STOP_RECORD = auto()

@dataclass
@annotate.final
@annotate.autoid("sequential")
class TeleopCommand_(idl.IdlStruct, typename="dobot_atom.msg.dds_.TeleopCommand_"):
    command_type: 'dobot_atom.msg.dds_.TeleopCommandType'


